### ISSUE TITLE
Error: Cannot find module 'bkjs-utils'

### ISSUE THREAD

**Issue by aminemaarouf** [vseryakov/backendjs#3]
just installed backendjs with npm, runing ` var bkjs = require('backendjs')` and got this error : 

```
$ node
> var bkjs = require('backendjs')
Error: Cannot find module 'bkjs-utils'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\workspace\backendjs-example\node_modules\backendjs\lib\lib.js:16:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by vseryakov** [comment]
Any errors installing bkjs-utils during npm i backendjs ?

**Comment by aminemaarouf** [comment]
No :(
```
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 4.4.0-43-Microsoft
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "configure" "build"
gyp ERR! cwd /mnt/d/workspace/backendjs-example/node_modules/bkjs-utils
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by vseryakov** [comment]
Sorry, it requires node 6+, i just updated package.json and commited, will publish soon

**Comment by aminemaarouf** [comment]
I have the latest version of node on my machine v8.2.1

**Comment by vseryakov** [comment]
strange, it says above gyp ERR! node -v v0.10.25

**Comment by aminemaarouf** [comment]
Maybe you should add it  in engine section in package.json to force the node version
